# Generated by Django 4.2.6 on 2023-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0002_book_price_alter_book_pages_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Toatal_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
